/*
    testproject.h
    Generated by FMOD Designer v4.44.1 
*/

#ifndef TESTPROJECT_H
#define TESTPROJECT_H

/*
    Total number of events in the project
*/
const int EVENTCOUNT_TESTPROJECT = 1;

/*
    EventGroup/Event-relative indices
*/
const int EVENTGROUP_TESTPROJECT_UNTITLED = 0;
const int EVENTGROUPCOUNT_TESTPROJECT_UNTITLED = 1;
const int EVENT_TESTPROJECT_UNTITLED_1 = 0;

/*
    Project-unique event ids
*/
const int EVENTID_TESTPROJECT_UNTITLED_1 = 0;

const int EVENTCATEGORY_TESTPROJECT_MASTER = 0;
const int EVENTCATEGORYCOUNT_TESTPROJECT_MASTER = 1;

const int EVENTCATEGORY_TESTPROJECT_MASTER_MUSIC = 0;
const int EVENTCATEGORYCOUNT_TESTPROJECT_MASTER_MUSIC = 0;


/*
    Event GUIDs
*/
const char *EVENTGUID_TESTPROJECT_UNTITLED_1 = "{c8e8c286-9589-465a-846a-e9dd13402f54}";

#endif /* TESTPROJECT_H */
